server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 192.168.0.104:8848
      #server-addr: 116.25.152.11:8848
      #server-addr: 116.25.152.11:80
      #discovery:
      #  cluster-name: Beijing
mybatis:
  type-aliases-package: com.kk.user.pojo
  map-underscore-to-camel-case: true
logging:
  level:
    com.kk: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka