server.port=8081
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
mybatis.type-aliases-package=com.zwm.user.pojo
mybatis.configuration.use-actual-param-name=true
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.pattern.dateformat=MM-dd HH:mm:ss:SSS
spring.application.name=user-service
eureka.client.service-url.defaultZone=http://127.0.0.1:10086/eureka