server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.0.105:8848
      discovery:
        cluster-name: Beijing
        namespace: 4c07af9d-44c0-4058-8798-e071bcde4c27
        ephemeral: true
mybatis:
  type-aliases-package: com.kk.order.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-service