server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.56.1:8848
    sentinel:
      transport:
        dashboard: 192.168.56.1:8858
      web-context-unify: false
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true
logging:
  level:
    com.kk: debug
mybatis:
  type-aliases-package: com.kk.order.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl